### ISSUE TITLE
Register PostgreSQL.jl package

### ISSUE THREAD

**Issue by scls19fr** [JuliaDatabases/PostgreSQL.jl#49]
```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1 (2017-03-05 13:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> Pkg.add("PostgreSQL")
ERROR: unknown package PostgreSQL
 in macro expansion at ./pkg/entry.jl:53 [inlined]
 in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at ./task.jl:360
 in sync_end() at ./task.jl:311
 in macro expansion at ./task.jl:327 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:51
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:31
 in add(::String) at ./pkg/pkg.jl:100
```

**Comment by gbarz** [comment]
The PostgreSQL.jl package (as well as the DBI.jl package, which you may also need) are not in the standard place for Julia packages.    Try running the following lines from within Julia:

Pkg.clone("git://github.com/JuliaDB/PostgreSQL.jl")
Pkg.clone("git://github.com/JuliaDB/DBI.jl")

**Comment by scls19fr** [comment]
Registering these packages could be a good idea.

**Comment by jgoldfar** [comment]
Another option that would allow using PostgreSQL without the abstraction of DBI: https://github.com/MikeInnes/Requires.jl to conditionally include and test the DBI portion of the code.

Not sure who should/would make such a decision, but I could prepare a PR

**Comment by s-celles** [comment]
DBI.jl is now a registered package https://github.com/JuliaDatabases/DBInterface.jl/issues/13#issuecomment-572796269

Maybe PostgreSQL.jl can now be registered.

**Comment by s-celles** [comment]
Closing as I just saw that PostgreSQL.jl is now deprecated in favor of [LibPQ.jl](https://github.com/invenia/LibPQ.jl)
